services:
  mysql:
    image: mysql
    container_name: mytraining-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Simple123
      MYSQL_DATABASE: MyTraining
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - node-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 5000:8080
    networks:
      - node-network
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  node-network:
